### ISSUE TITLE
Bundle readiness for development or production usage

### ISSUE THREAD

**Issue by cachan** [HelisLT/settings-manager-bundle#23]
Hi - I came across this bundle when searching for configuration bundles for Symfony on [packagist](https://packagist.org/packages/helis/settings-manager-bundle) and it's great and handles many of my needs. Some of the other settings bundles don't leverage the latest Symfony or PHP features and I'm really excited that this one does.

I'm curious whether you think that this bundle is ready for development or production usage. I see that there's been a lot of activity (code commits and releases) and I'm wondering if you think the bundle is stable enough to be used by an application in production. I can certainly provide feedback on areas that we use.

**Comment by kdauzickas** [comment]
hey Christopher, this bundle has been running for more than a year in our projects that are in production. Give it a go and let us know what the experience was :)

**Comment by cachan** [comment]
Awesome, thanks!
