### ISSUE TITLE
Get settings by tags generate an issue

### ISSUE THREAD

**Issue by emulienfou** [HelisLT/settings-manager-bundle#55]
A new issue seems to be introduced recently when getting settings from a tag name.

If by example I try to do the next call from the **SettingsController::editAction()** method by example:
```php
$this->settingsManager->getEnabledSettingsByTag([$domainName], 'general');
```

I receive the next exception: `Warning: Invalid argument supplied for foreach()` but only if data are already saved in database and come from `orm`.
It seems in this case, the value of the field `tags` is `null` instead of getting the list of tags.

Error is located at line **93** of the file **src/Model/SettingModel.php** in the code `foreach ($this->tags as $tag)`

**Comment by martiis** [comment]
You need to setup relationship between settings and tags to use them. It's not yet documented :| or have you done it?

**Comment by emulienfou** [comment]
I did not setup a relationship between settings and tags. However, are you doing a ManyToMany relatioship?

**Comment by emulienfou** [comment]
Ok thanks, at this time I will use the relationship like the examples in the test cases.
For sure it will need to be improved for a better solution.

However, do you know why I got the next message when I try to save to database:
`The given entity of type 'Helis\SettingsManagerBundle\Model\TagModel' (Helis\SettingsManagerBundle\Model\TagModel@000000005b9d35da000000003f9ff4e6) has no identity/no id values set. It cannot be added to the identity map.`

**Comment by martiis** [comment]
Provider also needs to know about tag entity. I guess that will be it

https://github.com/HelisLT/settings-manager-bundle/blob/8784dbc2321e43b8f61551610661f1bc513441d6/src/Provider/DoctrineOrmSettingsProvider.php#L25

**Comment by emulienfou** [comment]
Off course, my bad. Closing the issue
