### ISSUE TITLE
Unknown column type "setting_type_enum" requested.

### ISSUE THREAD

**Issue by emulienfou** [HelisLT/settings-manager-bundle#59]
Hello @martiis,
everytime I nuke my application cache, I receive the next error message when I'm trying to clear the cache with `cache:clear`: 

`Unknown column type "setting_type_enum" requested. Any Doctrine type that you use has to be registered with \Doctrine\DBAL\Types\Type::addType(). You can get a list of all the known types with \Doctrine\DBAL\Types\Type::getTypesMap(). If this error occurs during database introspection then you might have forgotten to register all database types for a Doctrine Type. Use AbstractPlatform#registerDoctrineTypeMapping() or have your custom types implement Type#getMappedDatabaseTypes(). If the type name is empty you might have a problem with the cache or forgot some mapping information.`

Weird thing, because it seems you are already register this doctrine type at the next line:
https://github.com/HelisLT/settings-manager-bundle/blob/da3df6d7a88760c78d87b5cfd4df6c10fd6b6944/src/HelisSettingsManagerBundle.php#L19-L28

**Comment by martiis** [comment]
Hi,

just tried with new symfony project and sqlite, registered orm provider, then cache:warmup, cache:clear no errors. Even commented out doctrine type registration in bundle class, no error.

Only guess I have that somewhere your application tries to access doctrine services or even database during container compilation? Somewhere in compiler pass or container extensions.

**Comment by emulienfou** [comment]
Hi,
exactly it's on my side. Sorry for that non-issue.
Closing it now
