### ISSUE TITLE
Implementing WYSWYG interface for value

### ISSUE THREAD

**Issue by pratishta** [HelisLT/settings-manager-bundle#68]
Hi there - we're using settings to input and update HTML text for home pages, update messages and email templates in our application. We are currently trying to use a rich text editor (CKEditor 5) so that it's easier to update the HTML text in the settings' values. 

I'm coming up short though because CKEditor replaces the <textarea> element with its rich text editor. However, the settings value is an < input> element. I was thinking about overriding the edit.html.twig template with one that manually replaces <input> with <textarea> using jQuery. Is there a less clunky solution that you might recommend?

**Comment by martiis** [comment]
Hi, for faster result I would override edit.html.twig ATM. Also I was thinking how to make this easier and came up with an idea to make an ability to modify form on event or something, then it opens more possibilities, like using [FOSCKEditorBundle](https://symfony.com/doc/master/bundles/FOSCKEditorBundle/index.html), or even using CurrencyType/CountryType/UrlType/... on string, other numeric types on int/float settings. What do you think?

**Comment by pratishta** [comment]
Apologies for this incredibly late response but I did proceed with overriding the template. Allowing more flexibility with value types in the form would in very helpful for the future as well.
