### ISSUE TITLE
dispatch function in MenuBuilder

### ISSUE THREAD

**Issue by pratishta** [HelisLT/settings-manager-bundle#76]
Hello, 

I am using Symfony 4.4 in my application. When using this settings bundle, I see that the dispatch() function used in Helis\SettingsManagerBundle\Menu\MenuBuilder.php has the old signature with event as the second argument. This throws an error. 

I see that Helis\SettingsManagerBundle\Settings\EventManager differentiates between >= 4.3 and < 4.2 for the different dispatch functions but that EventManager is not used in MenuBuilder. Is there a way to get the correct order of arguments for the dispatch function? Or another way?

**Comment by martiis** [comment]
Hello,

thanks for the interest. I see you already did a pull request #75 but that will break legacy versions. I think for a quick solution we could use EventManager in MenuBuilder with a new method for menu event.

Something like:

`php
    public function dispatchConfigureMenu(ConfigureMenuEvent $event): void
    {
        if ($this->eventDispatcher instanceof ContractsEventDispatcherInterface) {
            // sf >= 4.3
            $this->eventDispatcher->dispatch($event, SettingsManagerEvents::CONFIGURE_MENU);
        } else {
            // sf < 4.2 legacy
            $this->eventDispatcher->dispatch(SettingsManagerEvents::CONFIGURE_MENU, $event);
        }
    }
`

Later when we drop legacy versions we will have only one class to change :)

**Comment by pratishta** [comment]
Hi, that makes sense, thanks for your response. I updated the pull request with your suggested changes. Does this look better? And better so as to not break legacy versions?

**Comment by martiis** [comment]
Yes, but we should drop it soon enough. PR looks good. Travis build failed tho, but not your fault. Ill try to check it tonight
